### ISSUE TITLE
Not working in Unity

### ISSUE THREAD

**Issue by CrHasher** [PlayFab/pf-af-devfuncs#11]
Hello,

If I put the ExecuteFunction.cs file in a Unity project I get a lot of errors. Was this file never meant to work in Unity?

How does someone ExecuteFunction localy in Unity?

Regards,
- Szilard

**Comment by MGudgin** [comment]
Hi, 

ExecuteFunction.cs is meant to go in a C# Azure Functions project, not a Unity project. Then, when you run the Azure Functions project locally, you can enable local debugging of Azure Functions Cloudscript which will cause the PlayFab Unity SDK to re-direct ExecuteFunction API calls to the Azure Functions app rather than calling the public PlayFab API endpoint. This allows you to debug your Azure Functions CloudScript more easily then trying to debug it via log messages in Azure itself.

To enable local debugging, you need to drop a file called playfab.local.settings.json in TMPDIR if you on Mac/Linux or in TEMP if you are on Windows. See readme.md for the details.

Hope this helps,

Gudge

**Comment by CrHasher** [comment]
It is how I started out, but it does not work:

Function is set up in the functions app
![image](https://user-images.githubusercontent.com/834518/117937195-63c98f80-b30e-11eb-859b-ef8a089d7e65.png)

Temp file is in place
![image](https://user-images.githubusercontent.com/834518/117937251-70e67e80-b30e-11eb-8ba8-f38b21e4778e.png)
Contents:
`
{ "LocalApiServer": "http://localhost:7071/api/" }
`

And C# SDK ignores that file:
![image](https://user-images.githubusercontent.com/834518/117937285-7a6fe680-b30e-11eb-9a5c-370429984ba7.png)

**Comment by CrHasher** [comment]
It is because of this:
```csharp
        public static string LocalApiServer
        {
            get
            {
-> #if NET45 || NETSTANDARD2_0 <- This means I can't use C# SDK in Unity, only the Unity SDK
                return PlayFabUtil.GetLocalSettingsFile().LocalApiServer;
#else
                return _localApiServer;
#endif
            }
#if !NET45 && !NETSTANDARD2_0
            set
            {
                _localApiServer = value;
            }
#endif
        }
```
What I want is code that can be reused and is not Unity specific that's why I use the C# SDK.

**Comment by minami-tea** [comment]
Hello.
I have the same situation.

I think an easy workaround is to specify the LocalAPIServer anywhere in the code.

`PlayFabSettings.LocalApiServer = "http://localhost:7071/api/";`

[Reference]
https://community.playfab.com/questions/50436/unity-c-sdk-localapiserver-cannot-be-specified-for.html

**Comment by CrHasher** [comment]
The above solution might work, but I just added the extra defines for C# SDK directly to test, and it works now:

#if NET45 || NETSTANDARD2_0 **|| UNITY_EDITOR || UNITY_STANDALONE**

**Comment by MGudgin** [comment]
Thanks for the great discussion. I've submitted a PR to amend the relevant #if directives to include UNITY_EDITOR and UNITY_STANDALONE in the C# SDK.

**Comment by MGudgin** [comment]
Sorry for the delay here. The fix has now been merged and should appear in the public SDK next week,

**Comment by CrHasher** [comment]
Thank you! It was not a blocker I made the changes myself, but nice that now its officially fixed.

**Comment by MGudgin** [comment]
The new SDK with the required changes has been published. Closing this issue.
